import type { Event } from "@/types/event";

export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    title: "Festival de Jazz 2025",
    description: "Disfruta de los mejores exponentes del jazz internacional",
    date: "2025-10-15",
    time: "19:00",
    location: "Teatro Nacional",
    price: "Gratis",
    category: "Música",
    image: "🎵",
    organizer: "Fundación Cultural Nacional",
    capacity: 500,
    duration: "3 horas",
    registered: true,
  },
  {
    id: "2",
    title: "Exposición de Arte Moderno",
    description: "Colección exclusiva de artistas contemporáneos",
    date: "2025-10-15",
    time: "10:00",
    location: "Museo de Arte",
    price: "$10",
    category: "Arte",
    image: "🎨",
    organizer: "Museo Nacional de Arte",
    duration: "Todo el día",
  },
  {
    id: "3",
    title: "Noche de Teatro",
    description: "Obra clásica interpretada por el elenco nacional",
    date: "2025-10-15",
    time: "20:30",
    location: "Teatro Principal",
    price: "$15",
    category: "Teatro",
    image: "🎭",
    organizer: "Compañía Nacional de Teatro",
    capacity: 300,
    duration: "2 horas",
    registered: true,
  },
  {
    id: "4",
    title: "Concierto de Rock Latino",
    description: "Las mejores bandas de rock en español",
    date: "2025-10-22",
    time: "21:00",
    location: "Estadio Municipal",
    price: "$25",
    category: "Música",
    image: "🎸",
    organizer: "Live Nation",
    capacity: 5000,
    duration: "4 horas",
  },
  {
    id: "5",
    title: "Ballet Clásico: El Lago de los Cisnes",
    description: "Presentación de la compañía nacional de ballet",
    date: "2025-10-22",
    time: "19:30",
    location: "Teatro de la Ópera",
    price: "$30",
    category: "Danza",
    image: "🩰",
    organizer: "Ballet Nacional",
    capacity: 800,
    duration: "2.5 horas",
    registered: true,
  },
  {
    id: "6",
    title: "Festival Gastronómico Internacional",
    description: "Degustación de platos de más de 20 países",
    date: "2025-10-28",
    time: "12:00",
    location: "Parque Central",
    price: "$5",
    category: "Gastronomía",
    image: "🍽️",
    organizer: "Asociación de Chefs",
    duration: "8 horas",
  },
  {
    id: "7",
    title: "Feria de Arte Urbano",
    description: "Muestra de arte callejero y grafiti",
    date: "2025-10-30",
    time: "14:00",
    location: "Plaza de las Artes",
    price: "Gratis",
    category: "Arte",
    image: "🎨",
    organizer: "Colectivo Urbano",
    duration: "6 horas",
  },
  {
    id: "8",
    title: "Festival de Cine Independiente",
    description: "Proyección de películas de cineastas emergentes",
    date: "2025-10-05",
    time: "18:00",
    location: "Cinemateca Nacional",
    price: "$8",
    category: "Festivales",
    image: "🎬",
    organizer: "Cinemateca Nacional",
    capacity: 200,
    duration: "5 horas",
  },
  {
    id: "9",
    title: "Concierto Sinfónico",
    description: "Obras maestras de la música clásica",
    date: "2025-10-22",
    time: "19:00",
    location: "Auditorio Nacional",
    price: "$20",
    category: "Música",
    image: "🎻",
    organizer: "Orquesta Sinfónica Nacional",
    capacity: 1000,
    duration: "2 horas",
  },
  {
    id: "10",
    title: "Stand Up Comedy Night",
    description: "Los mejores comediantes del momento",
    date: "2025-10-15",
    time: "21:30",
    location: "Club de la Comedia",
    price: "$12",
    category: "Teatro",
    image: "😂",
    organizer: "Comedy Club Productions",
    capacity: 150,
    duration: "2 horas",
  },
  {
    id: "11",
    title: "Recital de Piano",
    description: "Obras de Chopin y Beethoven",
    date: "2025-10-22",
    time: "18:30",
    location: "Conservatorio de Música",
    price: "Gratis",
    category: "Música",
    image: "🎹",
    organizer: "Conservatorio Nacional",
    capacity: 120,
    duration: "1.5 horas",
  },
  {
    id: "12",
    title: "Danza Folklórica Latinoamericana",
    description: "Tradiciones de 10 países de la región",
    date: "2025-10-19",
    time: "20:00",
    location: "Casa de la Cultura",
    price: "$8",
    category: "Danza",
    image: "💃",
    organizer: "Compañía de Danza Folklórica",
    capacity: 250,
    duration: "2 horas",
  },
  {
    id: "13",
    title: "Festival de Poesía",
    description: "Lecturas y recitales de poetas nacionales",
    date: "2025-10-21",
    time: "17:00",
    location: "Biblioteca Nacional",
    price: "Gratis",
    category: "Festivales",
    image: "📚",
    organizer: "Academia de la Lengua",
    duration: "4 horas",
  },
  {
    id: "14",
    title: "Muestra de Cine Clásico",
    description: "Películas icónicas del cine de oro",
    date: "2025-10-23",
    time: "19:30",
    location: "Cine Retro",
    price: "$6",
    category: "Festivales",
    image: "🎞️",
    organizer: "Club de Cine",
    capacity: 100,
    duration: "3 horas",
  },
  {
    id: "15",
    title: "Opera: Carmen",
    description: "La obra maestra de Bizet",
    date: "2025-10-24",
    time: "20:00",
    location: "Teatro de la Ópera",
    price: "$40",
    category: "Teatro",
    image: "🎭",
    organizer: "Compañía Nacional de Ópera",
    capacity: 600,
    duration: "3 horas",
  },
  {
    id: "16",
    title: "Festival de Food Trucks",
    description: "Gastronomía sobre ruedas",
    date: "2025-10-26",
    time: "11:00",
    location: "Explanada del Estadio",
    price: "Gratis",
    category: "Gastronomía",
    image: "🚚",
    organizer: "Asociación de Food Trucks",
    duration: "10 horas",
  },
  {
    id: "17",
    title: "Taller de Fotografía Urbana",
    description: "Aprende técnicas de fotografía callejera",
    date: "2025-10-27",
    time: "10:00",
    location: "Centro Cultural",
    price: "$15",
    category: "Arte",
    image: "📷",
    organizer: "Escuela de Fotografía",
    capacity: 30,
    duration: "4 horas",
  },
  {
    id: "18",
    title: "Jam Session de Jazz",
    description: "Músicos improvisando en vivo",
    date: "2025-10-29",
    time: "22:00",
    location: "Jazz Café",
    price: "$10",
    category: "Música",
    image: "🎷",
    organizer: "Jazz Café",
    capacity: 80,
    duration: "3 horas",
  },
  {
    id: "19",
    title: "Festival de Otoño",
    description: "Música, arte y gastronomía al aire libre",
    date: "2025-10-31",
    time: "13:00",
    location: "Parque de la Ciudad",
    price: "Gratis",
    category: "Festivales",
    image: "🌸",
    organizer: "Municipalidad",
    duration: "8 horas",
  },
  {
    id: "20",
    title: "Tango en la Plaza",
    description: "Demostración y clases gratuitas",
    date: "2025-10-12",
    time: "18:00",
    location: "Plaza Mayor",
    price: "Gratis",
    category: "Danza",
    image: "💫",
    organizer: "Academia de Tango",
    duration: "2 horas",
  },
];
